# Generated by Django 4.2.2 on 2023-10-31 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "Syllabus_Project",
            "0002_customerinfo_iteminfo_alter_section_section_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cusName", models.CharField(max_length=40)),
                ("cusAddress", models.CharField(blank=True, max_length=20, null=True)),
                ("phoneNumber", models.CharField(blank=True, max_length=40)),
                ("email", models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ItemName", models.CharField(max_length=40)),
                ("ItemNumber", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderNum", models.IntegerField(unique=True)),
                ("orderDate", models.DateField()),
                ("orderAmount", models.IntegerField()),
                (
                    "Customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Syllabus_Project.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salesAmmmount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Syllabus_Project.orders",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ItemInfo",
        ),
        migrations.RemoveField(
            model_name="salesdata",
            name="Sales_Customer",
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="email",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="phoneNumber",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.DeleteModel(
            name="CustomerInfo",
        ),
        migrations.DeleteModel(
            name="SalesData",
        ),
    ]
