# Generated by Django 4.2.2 on 2023-10-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Syllabus_Project",
            "0003_customer_items_orders_sales_delete_iteminfo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("TA", "TA"),
                    ("Instructor", "Instructor"),
                    ("Admin", "Admin"),
                    ("SalesRep", "SalesRep"),
                    ("SalesAdmin", "SalesAdmin"),
                    ("HR", "HR"),
                    ("Operations", "Ops"),
                ],
                max_length=20,
            ),
        ),
    ]
