# Generated by Django 4.2.2 on 2023-10-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0006_alter_users_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="name",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
