# Generated by Django 4.2.2 on 2023-10-31 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0010_alter_users_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="name",
        ),
    ]
