# Generated by Django 4.2.2 on 2023-10-31 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0011_remove_users_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sales",
        ),
    ]
