# Generated by Django 4.2.7 on 2023-11-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0012_delete_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="region",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
