# Generated by Django 4.2.7 on 2023-11-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0013_users_region_alter_users_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Syllabus_Project.items",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="Syllabus_Project.orders",
                    ),
                ),
            ],
        ),
    ]
