# Generated by Django 4.2.7 on 2023-11-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0014_orderitems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="orders",
            name="orderAmount",
            field=models.IntegerField(default=0),
        ),
    ]
