# Generated by Django 4.2.7 on 2023-11-18 22:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0015_alter_customer_email_alter_orders_orderamount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emp_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("pay_rate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("hours", models.IntegerField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Syllabus_Project.users",
                    ),
                ),
            ],
        ),
    ]
