# Generated by Django 4.2.7 on 2023-11-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0016_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="day",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="officeLocation",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="officeNumber",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="timeFrom",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="timeTo",
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
