# Generated by Django 4.2.7 on 2023-11-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0017_remove_personalinfo_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hours",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
