# Generated by Django 4.2.7 on 2023-11-20 03:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "Syllabus_Project",
            "0019_employees_users_emp_id_delete_employee_employees_emp",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emp_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("pay_rate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("hours", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="users",
            name="hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="pay_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.DeleteModel(
            name="Employees",
        ),
        migrations.AddField(
            model_name="employee",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Syllabus_Project.users",
            ),
        ),
    ]
