# Generated by Django 4.2.7 on 2023-11-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0022_customer_cuszip"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cusState",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
