# Generated by Django 4.2.7 on 2023-11-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0027_orders_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="cusName",
            new_name="cusFirstName",
        ),
        migrations.AddField(
            model_name="customer",
            name="CusLastName",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AddField(
            model_name="customer",
            name="cusPassword",
            field=models.CharField(
                default="<django.db.models.fields.CharField><django.db.models.fields.CharField>",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="cusUsername",
            field=models.CharField(
                default="<django.db.models.fields.CharField><django.db.models.fields.CharField>",
                max_length=80,
            ),
        ),
    ]
