# Generated by Django 4.2.7 on 2023-12-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0028_rename_cusname_customer_cusfirstname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="cusPassword",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="cusUsername",
        ),
        migrations.AddField(
            model_name="customer",
            name="CusUser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Syllabus_Project.users",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="Customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Syllabus_Project.customer",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("SalesRep", "SalesRep"),
                    ("SalesAdmin", "SalesAdmin"),
                    ("HR", "HR"),
                    ("Operations", "Operations"),
                    ("Customer", "Customer"),
                    ("TA", "TA"),
                    ("Instructor", "Instructor"),
                ],
                max_length=20,
            ),
        ),
    ]
