# Generated by Django 4.2.7 on 2023-12-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0030_alter_users_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="CusUser",
        ),
        migrations.AddField(
            model_name="customer",
            name="cusPassword",
            field=models.CharField(
                default="<django.db.models.fields.CharField><django.db.models.fields.CharField>",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="cusUsername",
            field=models.CharField(
                default="<django.db.models.fields.CharField><django.db.models.fields.CharField>",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("SalesRep", "SalesRep"),
                    ("SalesAdmin", "SalesAdmin"),
                    ("HR", "HR"),
                    ("Operations", "Operations"),
                    ("TA", "TA"),
                    ("Instructor", "Instructor"),
                ],
                max_length=20,
            ),
        ),
    ]
