# Generated by Django 4.2.7 on 2023-12-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0032_alter_users_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Syllabus_Project.users",
            ),
        ),
    ]
