# Generated by Django 4.2.7 on 2023-12-02 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0033_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="cusPassword",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="cusUsername",
        ),
    ]
