# Generated by Django 4.2.7 on 2023-12-14 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0035_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="rep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Syllabus_Project.users",
            ),
        ),
    ]
