# Generated by Django 4.2.7 on 2023-12-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Syllabus_Project", "0036_task_rep"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="complete_notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
